### ISSUE TITLE
Kibana 5.5.x Support

### ISSUE THREAD

**Issue by blacksd** [ppadovani/KibanaNestedSupportPlugin#14]
Hi,
the description of the plugin stated "Kibana 5.x" but the `package.json` shows a dependency on Kibana 5.6.5. 
I did the unreasonable and changed the requirement to match my current review of Kibana/ES 5.5.3, repackaged the .zip and now I have the following error during install:

```sh
[blacksd@localhost ~]$ sudo /usr/share/kibana/bin/kibana-plugin install file://$PWD/nested-fields-support-1.0.0-beta2.zip 
Attempting to transfer from file:///home/blacksd/nested-fields-support-1.0.0-beta2.zip
Transferring 1953572 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    ERROR in /usr/share/kibana/plugins/nested-fields-support/public/nested_support/index_pattern/index_pattern.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /usr/share/kibana/src/ui/public/index_patterns/_get in /usr/share/kibana/plugins/nested-fields-support/public/nested_support/index_pattern
     @ /usr/share/kibana/plugins/nested-fields-support/public/nested_support/index_pattern/index_pattern.js 27:11-44
```

Any help appreciated.
Thanks,

Marco

**Comment by ppadovani** [comment]
Hi Marco,

Thank you for attempting to use this with 5.5.X! At this time, I have only been working against 5.6.5 in order to try and get to an initial release that I'm comfortable with. Once that has been done I'll create branches for versions in the past and the 6.x series. I have updated the README to reflect supported versions.

I'll leave this issue up to track 5.5.x support.

**Comment by blacksd** [comment]
Ok, I guess I'll go down the road of upgrading - thanks for the quick answer!

**Comment by chopchop505** [comment]
Looking forward to trying with 5.5.3 as well. Thanks!

**Comment by ppadovani** [comment]
5.5.3 support released.
