### ISSUE TITLE
Kibana 6.0.x Support

### ISSUE THREAD

**Issue by ppadovani** [ppadovani/KibanaNestedSupportPlugin#15]
Issue to track forward port to the 6.X series. I'll start on this after 1.0.0 has been cut w/ support for 5.6.X.

**Comment by ppadovani** [comment]
I will start on 6.0.X support this weekend.

**Comment by Hubbitus** [comment]
Hello @ppadovani. Firstly very thank you for the developing that plugin.

Could you please also make releases in repo and write short description how to install that plugin into `kibana` in binary mode?
Should I open separate issue?

**Comment by ppadovani** [comment]
Thanks for the feedback! I've updated the README to add installation instructions. I haven't yet started the 6.0 porting work, as a request came in to back port to 5.4 before I started the 6.0 work. As soon as I complete the 5.4 back port, I'll start on the 6.0 port.

**Comment by Hubbitus** [comment]
Thanks for the instructions but it seams incomplete.
Does 
```
Issue this command: bin/kibana-plugin install 
```
should be followed by URL of plugin?

When we may hope kibana 6.0 support will be available?

**Comment by ppadovani** [comment]
That was in the text, but I mistakenly used incorrect markdown, so it was hidden.. I fixed it in the current README.

I've been working on the 5.4 release, but I'll go take a quick look at the 6.0 release to see how hard it will be to implement. If it looks easier than the 5.4 is turning out to be, I'll switch to working on it first. I'll update this issue when I begin working on it and when I have an estimated release date.

**Comment by ayazahmedontech** [comment]
Hi @ppadovani , there is a huge change in kibana from 5.6 to 6.X . I think this will take lots of time.

**Comment by ppadovani** [comment]
Well, I was moving along at a great clip.. then ran across the fact that Kibana 6.0.1 has a SQL like language parser built into it. I could do one of two things here:

1. NOT port my SQL like language, and update their parser to recognize nested fields
2. Port my parser in and force users to use mine for nested index patterns.

The second option would be easier, whereas the first option would take significantly more time.

I will give this some thought. Suggestions/comments welcome.

**Comment by ayazahmedontech** [comment]
I guess second option is best if we are targeting only discovery view.

**Comment by ppadovani** [comment]
I spent some time looking at the new [Kibana language](https://www.elastic.co/guide/en/kibana/6.0/kuery-query.html)..... this is just an extension of the same field:value lucene language, but more in a functional form. The good news is that it looks like they made the query languages pluggable, so it can be selected on a per Kibana instance.

So, I will proceed with plugging in my SQL like language. I will likely keep the hack in that switches language based on the nested flag on the indexPattern however.

**Comment by ppadovani** [comment]
Anyone want to comment on an abbreviation for my query language? I was thinking something like:

knql - Kibana nested query language

**Comment by ppadovani** [comment]
Quick update:

- Discover app works, filters in discover app are still broken
- Aggregation visualizations work, result table is still broken.
- Some issues with the query bar still
- Query bar help link pointing to the wrong place

I anticipate another couple of days before I can release a version of this plugin.

**Comment by ppadovani** [comment]
I ran into a snag... it looks like I'm going to have to override the template used for certain angular routes in order to get the filter bar working. The Kibana team hard coded the filter bar to only work on lucene based queries.

**Comment by ppadovani** [comment]
I've released a beta 1 build.

Please open issues if there are bugs.

**Comment by ppadovani** [comment]
Found a solution to the filter bar.. aiming for an official 1.0 release this next weekend.

**Comment by ppadovani** [comment]
Merged and cut.

**Comment by Hubbitus** [comment]
Thank you very much for your work! I'll plan test it.
