### ISSUE TITLE
Kibana 5.4.0 version Support

### ISSUE THREAD

**Issue by hosnibenslama** [ppadovani/KibanaNestedSupportPlugin#22]

**Comment by ppadovani** [comment]
I'll work on a port this weekend.

**Comment by hosnibenslama** [comment]
@ppadovani  could you make a plugin for that version Thanks in advance

**Comment by ppadovani** [comment]
I'm splitting my time between 5.4 and 6.0 versions. I have a small blocker I need to figure out for 5.4. If I can get past it, I should be able to finish it pretty quickly.

**Comment by hosnibenslama** [comment]
Okay thanks :)

**Comment by ppadovani** [comment]
Got past a blocker this morning, I should be able to make quick work on the remainder of the port over the next few days. I expect to release this version this weekend.

**Comment by ppadovani** [comment]
Ran into another blocker. I am unable to override some of the factory classes that I need to, in order to inject my code. The pattern I'm using works fine in 5.5+-6.x so I'm going to have to find a different way to handle 5.4.

**Comment by hosnibenslama** [comment]
Please let me me know when you get past that blocker Thanks .

**Comment by ppadovani** [comment]
I may have found a solution, is this release still needed? If so I will take another stab at it this weekend, please let me know.

**Comment by ppadovani** [comment]
Too many releases to support, and I don't think I have a way around my blockers.

**Comment by IdanWo** [comment]
Is the same blocker heppears in all 5.x versions lower than 5.5? A suggestion in case of good luck: If, for example, kibana 5.3 is more suitable for the plugin, than @hosnibenslama can still use it (with a warning message thrown).

**Comment by ppadovani** [comment]
There are two main reasons why I will not attempt to back port below 5.5:

1. I already have too many releases to support and I am only one person. I also do this on the side. See this page for all of the current releases: https://ppadovani.github.io/knql_plugin/installation/

2. The issue with 5.4 and below is how Kibana loads the javascript. In many cases I have to replace functions on various objects BEFORE they are instantiated. This is just not possible in the previous versions, as that code runs BEFORE mine gets loaded.

Feel free to attempt the port yourself if interested.

**Comment by IdanWo** [comment]
Kibana 5.4.0 released more than a year ago (May 2017, to be exact). It's completly understood why supporting it isn't top priority at all, espcially when more than 6 releases already went out (and keep coming).
