### ISSUE TITLE
Query Parser: Add query script ability

### ISSUE THREAD

**Issue by ppadovani** [ppadovani/KibanaNestedSupportPlugin#24]
Add a new reserved word/symbol that allows the user to pass a script to elastic search per the built in script portion of the query engine. Something like:

Possible reserved words symbols:
```
foo=true AND SCRIPT("doc['maxCost'] - doc['minCost'] < 100")
```
```
foo=true AND #("doc['maxCost'] - doc['minCost'] < 100")
```
```
foo=true AND %("doc['maxCost'] - doc['minCost'] < 100")
```

The contents of the script would not be parsed, just packaged and sent to elastic search.

**Comment by IdanWo** [comment]
Must all of the fields inside the `doc ` be part of the root document? 
For example, Is there an option to make the following script?
`foo=true AND SCRIPT("doc[Car.Type]='Ford'")`
Priority: very low.
