### ISSUE TITLE
x-pack support

### ISSUE THREAD

**Issue by ppadovani** [ppadovani/KibanaNestedSupportPlugin#27]
From the comment left on the Kibana issue:

Thanks for your work and 6.0.1 release!

based on kibana 6.0.1, after installed this plugin, some kibana features doesnt work well.

when click timelion, it shows an error message:

-- shows an image with an error when attempting to use timelion. --

if x-pack installed, some x-pack feature "discover" has another error message in "Foreach"

@sccds

**Comment by ppadovani** [comment]
I have a fix for the error message... but I need stack traces from the javascript console to fix the others. I don't have x-pack installed....I'll install it after I get timelion working again. Totally my bad, I should have retested timelion prior to release.

**Comment by ppadovani** [comment]
I believe this is fixed, cutting and releasing.

**Comment by sccds** [comment]
Thank you very much!

When I using the plugin 6.0.1-1.0.1 and x-pack, the "discover" shows "ForEach" error.

![image](https://user-images.githubusercontent.com/6340346/35052063-9f0191a2-fbe1-11e7-9996-9457e9ae96de.png)

For other tags of x-pack, no error. "timelion" fixed.

**Comment by ppadovani** [comment]
I'll take a look... I thought I had fixed this...

**Comment by ppadovani** [comment]
I am unable to reproduce an error on the discover application with x-pack installed. Could this be related to a specific index mapping? Can you toggle the nested flag on the index in the management setup for this plugin?

**Comment by sccds** [comment]
thank you!
I have two kinds of data, one is nested, the other is not nested. I did select nested flag in the setup for the nested data. mapping like this:

```
PUT some_index_name
{
  "settings": {
    "index": {
      "number_of_shards": 5,
      "number_of_replicas": 1
    }
  },
  "mappings": {
    "xxx": {
      "properties": {
        "key1": {
          "type": "keyword"
        },
        "key2": {
          "type": "keyword"
        },
        "key3": {
          "type": "keyword"
        },
        "key4_nest": {
          "type": "nested",
          "properties": {
            "timestamp": {
              "type": "date",
              "format": "epoch_millis",
              "store": true
            },
            "some_text": {
              "type": "text",
              "store": true,
              "fields": {
                "cn": {
                  "type": "text",
                  "store": true,
                  "analyzer": "ik_max_word"
                },
                "en": {
                  "type": "text",
                  "store": true,
                  "analyzer": "english"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

```
PUT the_other_index
{
  "settings": {
    "index": {
      "number_of_shards": 5,
      "number_of_replicas": 1
    }
  },
  "mappings": {
    "xxx": {
      "properties": {
        "key1": {
          "type": "keyword"
        },
        "key2": {
          "type": "keyword"
        },
        "key3": {
          "type": "keyword"
        },
        "timestamp": {
          "type": "date"
        }
      }
    }
  }
}
```

I have to wait until tomorrow( I am in Asia timezone ) to provide more details.

**Comment by ppadovani** [comment]
For the security issue, looks like the default roles do not give the Kibana user access to:
indices:admin/mappings/get

This is needed by my plugin in order to load the nested field information. I'm playing with roles and privs to see if I can figure out how to get this working.

**Comment by yuyiyu2017** [comment]
@ppadovani Thanks for your plugin,it is very useful.but when I install the x-pack,the version of  5.6.5 also has this problem.

**Comment by ppadovani** [comment]
I changed the title of this issue to simply x-pack support. I've got some code that fixes a few things, but there are still some issues I'm working on. I'll get the support in place for the 6.0.1 plugin, then back port and test through all supported versions of my plugin. 

I would expect to have this fixed and released this weekend.

**Comment by ppadovani** [comment]
Ok, I think I have x-pack support working in 6.0.1. I made a mistake in how I configured the route for fetching index mappings. This support will require additional manual configuration of a role against a user in X-pack. I will document the setup steps in the README.md as part of the release. I want to continue some testing prior to release, so I'm still targeting this weekend to release the updated plugin.

Back-porting to the other releases should be pretty trivial, and I think I will be able to release all other version updates this weekend.

**Comment by ppadovani** [comment]
Had some time at lunch, released 6.0.1-1.0.2 w/ x-pack support. Please let me know if there are still issues with that version.

**Comment by ppadovani** [comment]
All releases updated to support x-pack.

**Comment by sccds** [comment]
I tried it, it is a great plugin!
Currently no new problem found.
Thank you very much!
