### ISSUE TITLE
(Kibana 5.5.3 nested support 1.0.1)this release with x-pack error.

### ISSUE THREAD

**Issue by czb1n** [ppadovani/KibanaNestedSupportPlugin#30]
Uncaught Error: [$injector:modulerr] Failed to instantiate module kibana due to:
Error: [$injector:unpr] Unknown provider: parseQueryDirectiveProvider
http://errors.angularjs.org/1.4.7/$injector/unpr?p0=parseQueryDirectiveProvider

**Comment by ppadovani** [comment]
Fix, and released

**Comment by czb1n** [comment]
thanks.

**Comment by yuyiyu2017** [comment]
@ppadovani thanks for your contribution. there is the same problem when I use the x-pack in the version of 5.6.5.
I do not know if it is my setup error or something else.
![default](https://user-images.githubusercontent.com/33891555/35262919-a7f7dca2-0051-11e8-9ae8-0c9a880fe0ba.png)

**Comment by ppadovani** [comment]
@yuyiyu2017 Thanks for the report, I'll port the fix over and build a new release today.

**Comment by ppadovani** [comment]
@yuyiyu2017 fixed and released.
