### ISSUE TITLE
v6.1.2-1.0.0: Optimizations failure - Unexpected token: operator (>)

### ISSUE THREAD

**Issue by tobiaswerner** [ppadovani/KibanaNestedSupportPlugin#33]
Hi Pierre,

thank you for your work and effort in making nested fields available in Kibana.
Unfortunately it fails when optimizing JavaScript/caching browser bundles.

Do you have an idea what's happening? 
I found some resources saying that babel do not run correctly or do not run the time it is intended to be run. 

`bin/kibana-plugin install file://<path-to>/nested-fields-support-6.1.2-1.0.0.zip`

```
Attempting to transfer from file://<path-to>/nested-fields-support-6.1.2-1.0.0.zip
Transferring 43344901 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.
   5183 modules

    ERROR in commons.bundle.js from UglifyJs
    Unexpected token: operator (>) [commons.bundle.js:251028,47]
"
```

I am running ElasticSearch and kibana both in version 6.1.2:
```
bin/kibana --version
6.1.2

bin/elasticsearch --version
Version: 6.1.2, Build: 5b1fea5/2018-01-10T02:35:59.208Z, JVM: 1.8.0_131
```

Any help is appreciated! :-)

**Comment by ppadovani** [comment]
I'll take a look at it.. I ran the plugin fine within my dev environment... I'll perform a normal install and try and duplicate your issue.

**Comment by ppadovani** [comment]
Quick update. Tracked this down to something with my query parser. Not quite sure what UglifyJs doesn't like about it.. so this might take a day or two to figure out a solution for.

**Comment by ppadovani** [comment]
fixed and released.

**Comment by tobiaswerner** [comment]
Unfortunately an error appears "SourceFormat is undefined".
![grafik](https://user-images.githubusercontent.com/1766562/35670251-4991978c-0738-11e8-80a1-f514c262f2ab.png)

Tried with latest release 6.1.2-1.0.2

**Comment by ppadovani** [comment]
I see the issue...

**Comment by ppadovani** [comment]
Released... please verify that 1.0.3 works for you. If so, please close this issue.

Thanks!

**Comment by tobiaswerner** [comment]
Very good 👍 Thank you!
