### ISSUE TITLE
Plugin installation was unsuccessful due to error "Optimizations failure.

### ISSUE THREAD

**Issue by open7c** [ppadovani/KibanaNestedSupportPlugin#34]
Version 6.1, Latest ELK-Stack inside Docker

```
root@4fc4096ed7b9:/opt/kibana# /opt/kibana/bin/kibana-plugin install file:///opt/kibana/plugins/KibanaNestedSupportPlugin-6.1.zip 
Attempting to transfer from file:///opt/kibana/plugins/KibanaNestedSupportPlugin-6.1.zip
Transferring 2558254 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.
   3717 modules
    
    ERROR in ./plugins/nested-fields-support/public/nested_support/parse_query/lib/from_user.js
    Module not found: Error: Can't resolve 'jison-gho' in '/opt/kibana/plugins/nested-fields-support/public/nested_support/parse_query/lib'
```

**Comment by open7c** [comment]
btw. i had to re-pack the zip file because the installation of the plugin is only working, when the plugin source inside the zip is inside of a **kibana** directory

**Comment by ppadovani** [comment]
That seems odd that you had to repackage the plugin. None of the other versions required this. I wonder if something changed with their plugin-helper scripts in terms of packaging. 

In terms of the missing module, that should have been shipped with the plugin during the build. Jison-gho is the Bison style parser that this plugin uses for the SQL like query syntax.

**Comment by ppadovani** [comment]
Can you please try the new 1.0.1 release for 6.1.2?

**Comment by open7c** [comment]
This Release is working, the installation succeeded. I had to re-pack the zip again, because the missing /kibana Directory where i put all the Source Code.
