### ISSUE TITLE
Kibana management index name hard coded, should pick up from server config

### ISSUE THREAD

**Issue by ppadovani** [ppadovani/KibanaNestedSupportPlugin#38]
**Plugin version**:
6.X

**Kibana version**:
6.X

**Description of the problem including expected versus actual behavior**:
With the new Version i get the following Error when i check an Index Pattern:

PUT https://kibana.example.com/api/saved_objects/index-pattern/3ad283a0-01c5-11e8-9be8-33ccd18ae84c 400 (Bad Request)

Error: mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed: [strict_dynamic_mapping_exception] mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed
at commons.bundle.js?v=16363:27
at processQueue (commons.bundle.js?v=16363:55)
at commons.bundle.js?v=16363:55
at Scope.$digest (commons.bundle.js?v=16363:55)
at Scope.$apply (commons.bundle.js?v=16363:55)
at done (commons.bundle.js?v=16363:55)
at completeRequest (commons.bundle.js?v=16363:55)
at XMLHttpRequest.xhr.onload (commons.bundle.js?v=16363:55) "Possibly unhandled rejection: {"statusCode":400,"body":{"message":"mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed: [strict_dynamic_mapping_exception] mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed","statusCode":400,"error":"Bad Request"}}"
I tried to find a solution, but haven't found one. Is this related to this Plugin or where can i adjust this strict/dynamic Setting? The Index was created automatically while we imported nested JSON Data into it.

**Steps to reproduce**:
Clean install of Kibana + Elasticsearch without the .kibana index created.

Workaround: Restart Kibana.

**Comment by ppadovani** [comment]
@open7c - Lets use this to track your issue.

**Comment by open7c** [comment]
A restart of Kibana doesn't change anything.

On my Installation there is no .kibana Index but a .kibana-6.

I can remember that this was because we started with Kibana 5 and due to the Migration to version 6 the official Docs said to create this .kibana-6 Index.

I think the cleanest way is to read the correct & current Value out of the Config File:

> **/opt/kibana/config/kibana.yml**
> kibana.index: ".kibana-6"

**Comment by ppadovani** [comment]
I'll take a deeper look this weekend, and see if I can get a solution together.

**Comment by ppadovani** [comment]
I just updated 6.1.3 to use the config of the server for the management index name. Can you please retry and let me know if this resolves your issue? If so I'll port the fixes to the other releases.

**Comment by open7c** [comment]
Bad News, Sir :-) In the meantime Kibana has changed from 6.1.3 to 6.2.1, so the Installer gives:

Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [nested-fields-support]. Expected [6.2.1]; found [6.1.3]"

**Comment by ppadovani** [comment]
FYI - You can control which version of Kibana is used by specifying a specific docker tag version.

Regardless, I've updated my 6.2.1 release to 1.0.1 with this fix. You will have to update your Dockerfile to point to the new version.

Let me know if this resolves your issue.

**Comment by open7c** [comment]
Yes, now the installation works and i can select Indices.

Now i have to figure out how to use it. In particular how KNQL works.

All Links to elastic.co on the page https://ppadovani.github.io/knql_plugin/overview/ are broken!

**Comment by ppadovani** [comment]
Yeah... figures... I'll update the links.. thanks for pointing that out.
