### ISSUE TITLE
Ability to support all kibana 5/6+ versions

### ISSUE THREAD

**Issue by ivanjunckes** [ppadovani/KibanaNestedSupportPlugin#39]
I would like to know if it is possible that the plugin doesn't require the specific minor versions to work. I see that we need to have a release at this moment for each version like 5.6.x. 

Would be very useful if we could use the same plugin version for all Kibana 5 versions, or for all Kibana 6 versions.

**Comment by ppadovani** [comment]
Unfortunately, this isn't something I can support for two reasons:

1. https://www.elastic.co/guide/en/kibana/current/plugin-development.html
2. This plugin overrides many base Javascript classes that ship with Kibana, and they may fix or enhance them in some way. With each release I check the changes that were committed to see what if any changes may affect the functionality that I've implemented.

I too wish that I could only release one version per 5.6.x, as it would make my life easier!
