### ISSUE TITLE
Issue with the search

### ISSUE THREAD

**Issue by ivanjunckes** [ppadovani/KibanaNestedSupportPlugin#40]
Kibana version: 5.6.5
When I type a search query, it doesn't work even when the syntax is right. Without the plugin this works very will.
![image](https://user-images.githubusercontent.com/2260551/36380361-be091884-1560-11e8-9e4f-56bfe7232e90.png)

**Comment by ppadovani** [comment]
This plugin uses its own query language. Please see this page for usage: https://ppadovani.github.io/knql_plugin/knql/

The language is very SQL like in nature and the above page explains the language.
