### ISSUE TITLE
Strange behavior in query

### ISSUE THREAD

**Issue by ivanjunckes** [ppadovani/KibanaNestedSupportPlugin#41]
Kibana version: 5.6.5
Query show as object object in a saved Dashboard.

![image](https://user-images.githubusercontent.com/2260551/36380543-6ba34348-1561-11e8-8c47-7bc99b780304.png)

**Comment by ppadovani** [comment]
Can you provide the steps that caused this behavior? I.e. what query was saved, how was the dashboard widget created etc.

**Comment by ivanjunckes** [comment]
Ok I realized the plugin has its own query language. It is probably related to that.
