### ISSUE TITLE
mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed

### ISSUE THREAD

**Issue by drewhemm** [ppadovani/KibanaNestedSupportPlugin#45]
**Plugin version**:

6.1.3-1.0.2

**Kibana version**:

6.1.3

**Plugins installed**:

No other plugins installed

**Description of the problem including expected versus actual behavior**:

I am attempting to create an index pattern after installing the KNQL plugin, but it fails every time with the output below. 

**Steps to reproduce**:
 1. Run ES, create a mapped index
 2. Run Kibana with KNQL plugin installed
 3. Attempt to create an index pattern

**Errors in browser console (if relevant)**:

Error: mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed: [strict_dynamic_mapping_exception] mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed
value/<@http://192.168.99.100:30368/bundles/commons.bundle.js?v=16371:27:106859
processQueue@http://192.168.99.100:30368/bundles/commons.bundle.js?v=16371:55:132456
scheduleProcessQueue/<@http://192.168.99.100:30368/bundles/commons.bundle.js?v=16371:55:133349
$digest@http://192.168.99.100:30368/bundles/commons.bundle.js?v=16371:55:144239
$apply@http://192.168.99.100:30368/bundles/commons.bundle.js?v=16371:55:147007
done@http://192.168.99.100:30368/bundles/commons.bundle.js?v=16371:55:100015
completeRequest@http://192.168.99.100:30368/bundles/commons.bundle.js?v=16371:55:104697
createHttpBackend/</xhr.onload@http://192.168.99.100:30368/bundles/commons.bundle.js?v=16371:55:105435

**Provide logs and/or server output (if relevant)**:

**If using docker, include your docker file**:

FROM docker.elastic.co/kibana/kibana-oss:6.1.3
RUN bin/kibana-plugin install https://github.com/ppadovani/KibanaNestedSupportPlugin/releases/download/6.1.3-1.0.2/nested-fields-support-6.1.3-1.0.2.zip

**Comment by ppadovani** [comment]
This is known, and has to do with startup order of the plugins. This plugin needs to modify the Kibana index and add additional fields. The current workaround is to restart the container. The initial load of Kibana will throw this error, then it will create the Kibana index. The subsequent startup of Kibana will properly modify the index. 

I will find some time to see if I can find a way to retry the index modify if it fails on startup to get this to work on the initial startup.

**Comment by drewhemm** [comment]
Cool. Confirmed restarting Kibana (in my Kubernetes case, deleting the pod and waiting for the new one) clears the error message. 

 Thanks :)

**Comment by sewalita** [comment]
Plugin version: 5.6.4-1.0.1
Kibana version: 5.6.4

Am getting the same error, restarting Kibana did not help.
What should the value of dynamic (true, false or strict) be in the  mapping?

Mapping used -
{
 "user_index": {
  "mappings": {
   "profile": {
	"properties": {
	  "age": {"type": "short"},
	  "user_id": {"type": "long"},
	  "gender": {"type": "keyword"},
	  "activity_nested": {
	    "type": "nested",
	    "properties": {
	      "activity_date": {"type": "date"},
		  "activity_type": {"type": "keyword"},
		  "channel": {"type": "keyword"}
	    }
	  }	
	}
   }
  }
 }
}

**Comment by sewalita** [comment]
@ppadovani 
Created https://github.com/ppadovani/KibanaNestedSupportPlugin/issues/58
I have x-Pack installed. 
Thank you.
