### ISSUE TITLE
Failed to pickup <Label for missing values> when nested type fields involved

### ISSUE THREAD

**Issue by androidkencai** [ppadovani/KibanaNestedSupportPlugin#48]
**Plugin version**:
[nested-fields-support-6.2.1-1.0.2.zip](https://github.com/ppadovani/KibanaNestedSupportPlugin/releases/download/6.2.1-1.0.2/nested-fields-support-6.2.1-1.0.2.zip)

**Kibana version**:
6.2.1
**Plugins installed**:
KibanaNestedSupportPlugin

**Description of the problem including expected versus actual behavior**:
As title. Also, the problem did not appear If the field is non-nested type. 
**Steps to reproduce**:
 1. New a datatable VIS from UI and add the following configuration in the Editor
Metric - Aggregation: Count
Buckets - Split Rows - Aggregation: Terms
Buckets - Split Rows - Field: <a nested field>
 2. Enabling the check-box of **Show missing values**, and enter a label in **Label for missing values**
 3. The label entered doesn't appear on the UI, but always showing __missing__

**Comment by ppadovani** [comment]
Thanks for the report, I'll take a look at this in the next day or so.

**Comment by ppadovani** [comment]
Fixed and released 6.2.1-1.0.3
