### ISSUE TITLE
Scripted fields compatibility

### ISSUE THREAD

**Issue by marlen2610** [ppadovani/KibanaNestedSupportPlugin#52]
**Plugin version**: 6.2.1-1.0.2

**Kibana version**: 6.2.1

**Description of the problem including expected versus actual behavior**: Scripted fields creation is not working after plugin installation

**Steps to reproduce**:
 1. Create a scripted field after NestedSupportPlugin installation
 2. See error in browser console
 3. The scripted field is not created

**Errors in browser console (if relevant)**:
ReferenceError: 'FieldFormat' is undefined...

**Comment by ppadovani** [comment]
I believe I have fixed the issue. I have cut 6.2.1-1.0.4, please test the new release and let me know if it resolves the issue, then I will port the fix to the other releases that are affected.

Thanks for the bug report!

**Comment by ppadovani** [comment]
Closing, I believe this is fixed. Please re-open if you find an issue.
