### ISSUE TITLE
Incorrect displayed order in visualizations when using "Use count of parent document" 

### ISSUE THREAD

**Issue by dtheodor** [ppadovani/KibanaNestedSupportPlugin#55]
_Running Kibana 6.2.2, tried this with all plugin releases for this version_

When doing a terms aggregation where the term belongs to a nested document and the metric is the Count of the parent doc (by clicking "Use count of parent document"), the order with which the buckets appear in the visualizations is wrong. I think that the order used is still the count of the nested documents, not the count of the parent doc.

This is purely a visual/UI issue, the query as well as the data displayed are correct, the top X is calculated using the count of the parent doc. It's just that the graph displays the different final buckets in the wrong order.

Example screenshots:

This is a bar chart that shows the wrong order

![screenshot 166](https://user-images.githubusercontent.com/1549648/37893107-ae71ba6e-30e2-11e8-9f79-115bbfb4c6e9.png)

This is the same bar chart but without  "Use count of parent document", where the order is correct. The colors correspond to the same buckets in both charts.

![screenshot 165](https://user-images.githubusercontent.com/1549648/37893123-bdfa28ae-30e2-11e8-8d81-18909522dc81.png)

**Comment by ppadovani** [comment]
Ok.. updated the 1.0.2 build with a fix for this.. please test and let me know.

**Comment by dtheodor** [comment]
Looks fixed
