### ISSUE TITLE
Split Charts shows empty Visualization

### ISSUE THREAD

**Issue by bgeVam** [ppadovani/KibanaNestedSupportPlugin#56]
**Plugin version**: 6.2.2-1.0.2

**Kibana version**: 6.2.2 

**Plugins installed**: -

**Description of the problem including expected versus actual behavior**:
Expected Behavior: Chart is displayed, Split Series works fine

Inserted Data:

    "fall": "123456",
    "mandant": "RKB",
    "anreise": "2017-12-01 08:00:00",
    "abreise": "2017-12-22 08:00:00",
    "scores": [
      {
        "date": "2017-12-01 08:00:00",
        "label": "1.12.2017",
        "type": "TUG",
        "value": 23
      },
      {
        "date": "2017-11-01 08:00:00",
        "label": "1.11.2017",
        "type": "TUG",
        "value": 44
      },
      {
        "date": "2017-12-01 08:00:00",
        "label": "1.12.2017",
        "type": "FBA",
        "value": 22
      },
      {
        "date": "2017-11-01 08:00:00",
        "label": "1.11.2017",
        "type": "FBA",
        "value": 31
      }
    ]
  

Split Series works fine:

![works](https://user-images.githubusercontent.com/11328579/37961348-501a5076-31b8-11e8-920b-6fc6e17319d0.PNG)

Split Charts stays empty:

![broken](https://user-images.githubusercontent.com/11328579/37961349-5036a8a2-31b8-11e8-98b6-2cea61733bd4.PNG)

The table below shows, the values are there.

**Errors in browser console (if relevant)**:
![browser error](https://user-images.githubusercontent.com/11328579/37961515-c92d125a-31b8-11e8-8be8-b866e93105c3.PNG)

**Comment by ppadovani** [comment]
FYI - the 1.0.2 release for Kibana 6.2.2 is not officially released. :-)

I'll take a look at this, and use this same release that is pending to fix this.

**Comment by ppadovani** [comment]
Ok... found the bug I believe. Can you please re-test? I was able to correctly split bar charts. If this fixes the issue, please indicate so but do not close the issue. I will close the issue after I have ported the fix to all releases.

Thanks!

**Comment by bgeVam** [comment]
Could you compile for me? I won't be able to test until tuesday, but then I will for sure! Thanks for your quick reply, AND:

Thanks a lot for creating this wonderful plugin! :+1:

**Comment by ppadovani** [comment]
It is compiled... located here: https://github.com/ppadovani/KibanaNestedSupportPlugin/releases/download/6.2.2-1.0.1/nested-fields-support-6.2.2-1.0.2.zip

As soon as you verify, I'll officially cut the release and begin porting the fixes.

**Comment by bgeVam** [comment]
Thank you, that solved the issue!
