### ISSUE TITLE
Range filter not generating nested queries in Kibana 6.2.2

### ISSUE THREAD

**Issue by erkserkserks** [ppadovani/KibanaNestedSupportPlugin#59]
**Plugin version**:
5.6.6-1.0.2, 6.2.2-1.0.3

**Kibana version**:
5.6.6, 6.2.2

**Plugins installed**:
KNQL only

**Description of the problem including expected versus actual behavior**:
The test data was generated using `scripts/nested-support/genData.py`

In Kibana 5.6.6, applying range filters does the right thing and produces a nested query.
In Kibana 6.2.2, applying range filters does the wrong thing and does not produce a nested query.

**Kibana 5.6.6 does the right thing:**
![kibana_5 6 6_before](https://user-images.githubusercontent.com/2941377/38707644-39645050-3e80-11e8-8995-3eadaf516b1d.png)
![kibana_5 6 6_after](https://user-images.githubusercontent.com/2941377/38707653-3f678c4c-3e80-11e8-8e89-219e8bfd3530.png)

**Kibana 6.2.2 does the wrong thing:**
![kibana_6 2 2_before](https://user-images.githubusercontent.com/2941377/38707686-59597142-3e80-11e8-88de-bcde6d069c6b.png)
![kibana_6 2 2_after](https://user-images.githubusercontent.com/2941377/38707690-5e4caa48-3e80-11e8-938c-6b7b392236ce.png)

**This also happens in discover.**
Right thing:
![kibana_5 6 6_discover](https://user-images.githubusercontent.com/2941377/38707700-71d906b0-3e80-11e8-8b7a-da2d85bb9964.png)
Wrong thing:
![kibana_6 2 2_discover](https://user-images.githubusercontent.com/2941377/38707706-7c51034a-3e80-11e8-9643-c3a2232b5aa4.png)

While investigating this, I also found that some filters (built using the "Add a filter" UI) work only in certain versions of Kibana:
- is - Works in Kibana 5 and 6
- is one of - Does not work in Kibana 5 nor 6
- is between - Works in Kibana 5, does not work in 6
- exists - Does not work in Kibana 5, works in 6

**Comment by ppadovani** [comment]
Now **THIS** is a bug report! Many thanks for the details. I should be able to resolve most of these in the next day or so.

**Comment by ppadovani** [comment]
Ok.. There was a major update in Kibana that happened from 5.x to 6.x, and it looks like the work I did on range filters did not make it... should be fixed in the latest 6.2.2-1.04. 

Please take a look if it solves the issue, please update this issue, but don't close it. I'll use this to port the fix to other releases, and close this when done.

**Comment by erkserkserks** [comment]
Wow, thanks for the quick response! I can confirm that it fixes the range filter issue :)

**Comment by ppadovani** [comment]
Back ported to all supported 6.X+++ releases

**Comment by ppadovani** [comment]
Ported to: 5.6.7, 5.6.8 and 5.6.9

**Comment by ppadovani** [comment]
done
