### ISSUE TITLE
would you mind to provide a screenshot?

### ISSUE THREAD

**Issue by xycloud** [ppadovani/KibanaNestedSupportPlugin#6]

**Comment by ppadovani** [comment]
The first issue I'm working on is the [management](https://github.com/ppadovani/KibanaNestedSupportPlugin/issues/3) aspect. I've had to spend time learning how to write a Kibana plugin. Please see/monitor the other issues for progress and screenshots. In terms of what the end product will look like, it will be very similar to my fork of [Kibana](https://github.com/homeaway/kibana/tree/nestedSupport-5.2).
