### ISSUE TITLE
Dashboard with pie chart visualization (with unique count metric aggregation) is showing error "Visualize: AggConfig is not defined"

### ISSUE THREAD

**Issue by mridul-tamuli** [ppadovani/KibanaNestedSupportPlugin#62]
**Plugin version**: 5.6.4-1.0.1

**Kibana version**: 5.6.4

**Other Plugins installed**: X-pack version 5.6.4

**Description of the problem including expected versus actual behavior**: 
Dashboard is showing error "Visualize: AggConfig is not defined." and some pie charts with "unique count" metric aggregation are not showing.

Also in the search bar text field "[object Object]" appearing instead of the placeholder "Search... (e.g. status:200 AND extension:PHP)" after installing and enabling the nested support plugin. 

**Steps to reproduce**:
 1. Install the Kibana Nested Support plugin  
 2. Create one pie chart visualization with metric aggregation "Unique Count" of a field 

**Errors in browser console (if relevant)**:
ReferenceError: AggConfig is not defined
    at http://localhost:5601/bundles/commons.bundle.js?v=15571:160:3028
    at Array.forEach (<anonymous>)
    at http://localhost:5601/bundles/commons.bundle.js?v=15571:160:2953
    at Array.forEach (<anonymous>)
    at AggConfigs.toDsl (http://localhost:5601/bundles/commons.bundle.js?v=15571:160:2211)
    at http://localhost:5601/bundles/kibana.bundle.js?v=15571:83:24729
    at SearchSourceProvider.SearchSource._mergeProp (http://localhost:5601/bundles/commons.bundle.js?v=15571:118:31013)
    at ittr (http://localhost:5601/bundles/commons.bundle.js?v=15571:158:23395)
    at http://localhost:5601/bundles/commons.bundle.js?v=15571:145:9878
    at http://localhost:5601/bundles/commons.bundle.js?v=15571:145:20114

Please help. Thanks in advance.

**Comment by ppadovani** [comment]
I believe I had this issue with my plugin in the 6.x support. I'll take a look at this. I may not have a fix until the weekend due to availability.

**Comment by ppadovani** [comment]
It will be a few more days before I can look at this.

**Comment by ppadovani** [comment]
Can you please retest with my latest release? I have backported a number of fixes.

**Comment by ppadovani** [comment]
please reopen if this is still an issue.

**Comment by yrcumt** [comment]
I got this error, too. https://github.com/ppadovani/KibanaNestedSupportPlugin/issues/104
