### ISSUE TITLE
Percentile aggregations don't work on nested fields

### ISSUE THREAD

**Issue by erkserkserks** [ppadovani/KibanaNestedSupportPlugin#63]
**Plugin version**:
6.2.2-1.0.4 and 5.6.6-1.0.2

**Kibana version**:
6.2.2 and 5.6.6

**Plugins installed**:
KNQL only

**Description of the problem including expected versus actual behavior**:
Percentile aggregations don't work on nested fields. I have also encountered this issue with the standard deviation, median, and percentile ranks aggregations.

The test data was generated using `scripts/nested-support/genData.py`
Both Kibana 5.6.6 and 6.2.2 have the same bug.

**This does the right thing (Non-nested field)**:
![expected](https://user-images.githubusercontent.com/2941377/38942875-0183ff8c-42fe-11e8-9f77-6f8e623622ea.png)

**This does the wrong thing (Nested field)**:
![actual](https://user-images.githubusercontent.com/2941377/38942995-4bd0bf80-42fe-11e8-96ad-bc7ea8b373ab.png)

We seem to be getting a valid elasticsearch response with nested field, but the response is not rendered properly
![actual response](https://user-images.githubusercontent.com/2941377/38943058-74ab4e5c-42fe-11e8-8909-3af56cc2040c.png)

**Errors in browser console (if relevant)**:
There wasn't anything interesting in the console before these rendering errors.
![console log](https://user-images.githubusercontent.com/2941377/38940438-20cf1742-42f8-11e8-8525-6364bfab26e8.png)

**Comment by erkserkserks** [comment]
No worries! Thanks for taking a look :)

**Comment by ppadovani** [comment]
Ok.. I have these fixed locally... I'm going to track down the other two issues, then I'll cut a release.

**Comment by ppadovani** [comment]
Fixed in 6.2.2, 6.2.3, 6.2.4 

Will begin back porting tomorrow.

**Comment by ppadovani** [comment]
Fixed in 6.2.1

**Comment by ppadovani** [comment]
Back ported to all supported 6.X+++ releases

**Comment by ppadovani** [comment]
Ported to: 5.6.7, 5.6.8 and 5.6.9

**Comment by ppadovani** [comment]
done
