### ISSUE TITLE
Unable to bucket by nested field with multiple Y-axis metrics

### ISSUE THREAD

**Issue by erkserkserks** [ppadovani/KibanaNestedSupportPlugin#64]
Another day, another bug report :)

**Plugin version**:
6.2.2-1.0.4 and 5.6.6-1.0.2

**Kibana version**:
6.2.2 and 5.6.6

**Plugins installed**:
KNQL only

**Description of the problem including expected versus actual behavior**:
When creating visualizations with multiple Y-axis metrics, it is not possible to bucket by a nested field.

The test data was generated using `scripts/nested-support/genData.py`
Both Kibana 5.6.6 and 6.2.2 have the same bug.
 
**Correct behavior when bucketing by a non-nested field (both min and max metrics are visible):**
![correct](https://user-images.githubusercontent.com/2941377/39020999-e9e4bb3c-43fc-11e8-9ba7-c41e631658fb.png)

**Incorrect behavior when bucketing by a nested field (missing min metric):**
![incorrect](https://user-images.githubusercontent.com/2941377/39021002-f0776562-43fc-11e8-8376-ad17a717c5ed.png)
![incorrect table](https://user-images.githubusercontent.com/2941377/39021437-c2f4823a-43fe-11e8-9470-c924e408adfb.png)

I believe that an incorrect elasticsearch request is generated (left side). A correct request should look something like the right side.
![incorrect_vs_correct](https://user-images.githubusercontent.com/2941377/39021295-25a16dc2-43fe-11e8-92a0-798aaf41af02.png)

**Errors in browser console (if relevant)**:
No errors in console

**Comment by ppadovani** [comment]
Good find here... this one is going to be tricky, as it is within the core aggregation generation code that I put in place. This will take another day or so to get right.

**Comment by ppadovani** [comment]
Fixed in 6.2.2, 6.2.3, 6.2.4 

Will begin back porting tomorrow.

**Comment by erkserkserks** [comment]
Thanks for all your work! :)

**Comment by ppadovani** [comment]
Fixed in 6.2.1

**Comment by ppadovani** [comment]
Ported to: 5.6.7, 5.6.8 and 5.6.9

**Comment by ppadovani** [comment]
done
