### ISSUE TITLE
Null object issues in discover

### ISSUE THREAD

**Issue by guinoise** [ppadovani/KibanaNestedSupportPlugin#65]
**Plugin version**: 6.2.2

**Kibana version**: 6.2.3 (tested with 6.2.2 as well)

**Plugins installed**: x-pack

When the data contain a null (nil) value, it just doesn't show in the discover page. The hits count is correct, but no data are showned. 

If I disabled the nested plugin, the discover page handle this case by showing a dash (-) at the place of the null value.

**Steps to reproduce**:
 1. Insert data in elasticsearch with null value inside one property
 2. Go to discover page
 3. Search (hits count will show correctly, but no data displayed)

**Comment by ppadovani** [comment]
I'll look at this and fix with #63 #64 .

**Comment by ppadovani** [comment]
Working on debugging this... can you provide a bit more information?

- what query are you running
- what does the mapping look like
- what field has a null value

I can see the '-' in my sample data...
<img width="530" alt="screen shot 2018-04-23 at 7 41 16 am" src="https://user-images.githubusercontent.com/11234684/39127195-eb23b226-46c9-11e8-855c-14b8d1e43c95.png">

**Comment by ppadovani** [comment]
I'm going to pause on this issue, and release the fixes I have for 6.2.X. As soon as you can provide additional reproduction details I take a look at this again.

**Comment by guinoise** [comment]
Hi,
Try with this :
`
PUT /_template/test
{
  "index_patterns": [
    "test-*"
  ],
  "mappings": {
    "doc": {
      "_meta": {
        "version": "1.0.0"
      },
      "properties": {
        "@timestamp": {
          "type": "date"
        },
        "@version": {
          "ignore_above": 256,
          "type": "keyword"
        },
        "customer": {
          "type": "nested",
          "properties": {
            "name": {
              "type": "keyword"
            },
            "address": {
              "type": "nested",
              "properties": {
                "city": {
                  "type": "keyword"
                },
                "postalCode": {
                  "type": "keyword"
                },
                "street": {
                  "type": "keyword"
                }
              }
            }
          }
        }
      }
    }
  }
}

POST /test/a
{
  "customer": {
    "name": null,
    "address": {
      "city": null,
      "postalCode": "H0H0H0",
      "street": null
    }
  }
}
`

![knql](https://user-images.githubusercontent.com/15348046/39260604-ff38de34-4887-11e8-8613-9ec80036ac1f.JPG)

**Comment by ppadovani** [comment]
Thanks! I'll take a look at this in the next day or so.

**Comment by ppadovani** [comment]
Fixed in 6.2.2, 6.2.3, 6.2.4 ... working to back port.

**Comment by ppadovani** [comment]
Back ported to all supported 6.X+++ releases

**Comment by ppadovani** [comment]
Ported to: 5.6.7, 5.6.8 and 5.6.9

**Comment by ppadovani** [comment]
Done
