### ISSUE TITLE
Please support kibana version 6.3

### ISSUE THREAD

**Issue by Hubbitus** [ppadovani/KibanaNestedSupportPlugin#78]

**Comment by ppadovani** [comment]
I'll get a port done in the next few days.

**Comment by ppadovani** [comment]
Be aware that the Kibana team has redone the development support in Kibana and moved from npm to yarn. This requires me to regenerate my plugin, so this isn't a simple quick port. However once I get things working, future ports should be easier... this may not get done until next weekend based on my free time.

**Comment by ppadovani** [comment]
I believe I should be able to complete the port this weekend.

**Comment by ppadovani** [comment]
Ever the optimist I am... looks like they rewrote the typeahead code related to the query bar. None of my existing code will work with their new code. I don't know how long this will take to rewrite yet. I'll update status when I have a better idea on a target.

**Comment by ppadovani** [comment]
Quick update: I've got discover working with my parser again, but am still working on the error handling and type ahead. Most of the aggregation code seems to be working with some minor issues around std deviation, based on my regression dashboard. I should have a release by next weekend, unless I find some time to work on this during the week.

**Comment by ppadovani** [comment]
Quick Poll. I can release this weekend **WITHOUT** typeahead and syntax error handling. The amount of work I'm going to have to do in order to bring that online is significant due to the reorganization of the Kibana code.

Sound off... should I release without those pieces to unblock people, and release a new version in a few weeks with them, or just get it all done and force everyone to wait a few more weeks?

**Comment by SavchenkoValeriy** [comment]
I can wait, it's not really critical at the moment.
BTW thank you for your great work!

**Comment by ppadovani** [comment]
Quick weekend update: The end is in sight. I have type ahead working. I only have to cleanup the display of the parse error message and fix the two broken aggregations. Then final testing. I see no reason at this point that would hold up the release from happening this next weekend.

**Comment by ppadovani** [comment]
Good news! Had some time to work on this today, got everything I can see working.

I want to take a look at the following issues to see if they exist in this release before I cut:
https://github.com/ppadovani/KibanaNestedSupportPlugin/issues/80
https://github.com/ppadovani/KibanaNestedSupportPlugin/issues/81
https://github.com/ppadovani/KibanaNestedSupportPlugin/issues/82

I still anticipate releasing no later than this weekend, but might release earlier depending upon what I find.

**Comment by ppadovani** [comment]
Ok... I may release this tomorrow... I want to spend another hour or so testing. #80 exposed another change I was not aware of and had no regression visualization in my dashboard. I've fixed that, which also exposed a few other issues which have also been fixed. The other issues referenced above are non-issues.

**Comment by ppadovani** [comment]
Released
