### ISSUE TITLE
Like (~=) operator token error on 5.6.7-1.0.1

### ISSUE THREAD

**Issue by jcsims** [ppadovani/KibanaNestedSupportPlugin#81]
**Plugin version**: 
5.6.7-1.0.1

**Kibana version**: 
5.6.7

**Plugins installed**: 
nested-fields-support, x-pack

**Description of the problem including expected versus actual behavior**:
Using a query with the `like` operator (`~=`) is failing in the Discover window, giving an error:
`Unexpected token { in JSON at position 25` (position changes, this particular error is from the query `host ~= "*"` as an example).

**Steps to reproduce**:
 1. Open the Discover pane, on an index pattern with nested support turned on
 2. Type in any query using the `~=` operator
 3. Notice the error message

**Errors in browser console (if relevant)**:
None

**Comment by ppadovani** [comment]
I'll be focusing time this weekend on new releases and bugs, so I should be able to take a look at this then.

**Comment by jcsims** [comment]
@ppadovani were you able to look into this? I'm trying to make some time this week to look into this bug.

**Comment by ppadovani** [comment]
Sorry, the port to 6.3 has taken more time than initially thought due to some of the re-org of the Kibana code... I should have 6.3 wrapped up this weekend. 

If you would like to look into this and submit a pull request that would be fantastic. If not, I don't see any reason why I can't knock this out this weekend as well.

**Comment by ppadovani** [comment]
I took a quick look at this in the 6.3 release I'm working on, and it seems to be working fine. I can use this query against my test data without an issue: cars.color~="*". 

If you don't submit a pull request before this weekend, I should be able to look at this at your specific release level.

**Comment by ppadovani** [comment]
Looks like a bug in the parser:
```
{"nested":{"path":"cars","query":{"bool":{"filter":{"wildcard":{"cars.color":"a"}}{"match_phrase":{"cars.color":"a"}}}}}}
```
Both a filter and match_phrase but without a separating comma... not sure the match_phrase should be there... this may have been introduced by a back port of a previous fix. This shouldn't take long to resolve.

**Comment by ppadovani** [comment]
Fixed and released.

**Comment by ppadovani** [comment]
Ooops... I want to leave this open to verify other releases and/or fix them if I propagated this bug.

**Comment by jcsims** [comment]
Thanks, will try to get this verified on my end today.

**Comment by ppadovani** [comment]
done
