### ISSUE TITLE
Version 6.3.1 Link is broken

### ISSUE THREAD

**Issue by mattan212** [ppadovani/KibanaNestedSupportPlugin#83]
The link to V6.3.1 is broken (see attached image).
Tried to access the zip link from your installation page:
https://github.com/ppadovani/KibanaNestedSupportPlugin/releases/download/6.3.1-1.0.9/nested-fields-support-6.3.1-1.0.0.zip

![image](https://user-images.githubusercontent.com/6297451/43293284-4614b414-90ee-11e8-8926-1480c5e77a8e.png)

**Comment by ppadovani** [comment]
Thanks for the heads up.. typo ... fixed now.
