### ISSUE TITLE
support query for field name in chinese

### ISSUE THREAD

**Issue by pingguoyuan** [ppadovani/KibanaNestedSupportPlugin#96]
**Describe the feature**: 
First, thank you so much for what you've done to solve "Nested" query problem of Kibana. 

The plugin does not work well when  keys or values of documents are in chinese. For example, one document is like {
"姓名": "原",
"性别": "男"
"教育经历":[....]   <nested>
} 
when I query in the Discover page by using " 姓名 = "原" ", no results matched.  anyting wrong in my operation, Or the plugin does not support chinese?

**Comment by ppadovani** [comment]
I don't know of a specific reason why this wouldn't work. I'll take a look in the next week or so.

**Comment by ppadovani** [comment]
I'm caught up, and will take a look at this tomorrow.

**Comment by pingguoyuan** [comment]
In the addition, when input Chinese field name for searching, it shows " Lexical error on line 1: Unrecognized text.", "Erroneous area:". It seems like that the search bar does not take the chinese characters, 姓名 or 性别, as field names.

**Comment by pingguoyuan** [comment]
Regular Expressions defined by the array "rules" in knql.js, they can not match unicode characters. I added "/* 35: */  /^(?:[\u4e00-\u9fa5]*)/" as a workaround.
