### ISSUE TITLE
6.4.2  - Error Editing Index Fields

### ISSUE THREAD

**Issue by Tishinator** [ppadovani/KibanaNestedSupportPlugin#98]
**Plugin version**: 6.4.2

**Kibana version**: 6.4.2

**Plugins installed**: KibanaNestedSupport(this one)

**Description of the problem including expected versus actual behavior**:
When you go to the Management UI ->Index Patterns and try and edit a field, it results in an error page.
The expected behavior is when you click the edit button it takes you to the edit UI for that specific field.

**_This behavior did not occur in the 6.3 version of the plugin_**

**Steps to reproduce**:
 1. Click on the Management Tab 
 2. Click on the Index Patterns option under Kibana
 3. Click on the edit button on any field (by hovering over the field the edit button will appear on the right)
4. [ACTUAL] Error page appears. [Expected] Edit field UI page

**Errors in browser console (if relevant)**:  
[Error not in console, rather on screen when you go to the edit field UI page]
`Uncaught TypeError: Cannot read property 'replace' of undefined (http://seismic-sigrepo:5601/bundles/vendors.bundle.js:227)`

**Provide logs and/or server output (if relevant)**: No Logging Errors occurred.

**If using docker, include your docker file**:

**Comment by ppadovani** [comment]
I should be able to fix this as part of a release this weekend along with #99

**Comment by ppadovani** [comment]
Fixed and released
