### ISSUE TITLE
Invalid aggregator order path [1]. 

### ISSUE THREAD

**Issue by huawangpp** [ppadovani/KibanaNestedSupportPlugin#99]
I still run into the issue with the aggregation nested object. Plugin version 6.4.0-1.0.0. The error messages are 

Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"aggregation_execution_exception","reason":"Invalid aggregator order path [1]. Unknown aggregation [1]"}]

It is similar to this issue https://github.com/ppadovani/KibanaNestedSupportPlugin/issues/54. But since I'm using a build with the fix, this might be a remaining bug?

The generated query is like below. You can see why the error message would occur.
```{
  "aggs": {
    "2": {
      "terms": {
        "field": "meta.log_guid.keyword",
        "size": 50,
        "order": {
          "1": "desc"
        }
      },
      "aggs": {
        "nested_1": {
          "nested": {
            "path": "sdv_hardware.host.fpga_stream"
          },
          "aggs": {
            "1": {
              "max": {
                "field": "sdv_hardware.host.fpga_stream.latency_max"
              }
            }
          }
        }
      }
    }
  }

**Comment by ppadovani** [comment]
Yes... this looks like a regression. The order should have read something like 'nested_1>1' . I'll see about getting a fix in place over the next few days while I'm on vacation.

**Comment by huawangpp** [comment]
Thanks for fast response.

**Comment by ppadovani** [comment]
Ok.. tracked down that a piece of my code was not being injected correctly, so the default Kibana code was being used. I'll get this fixed and get a new release out in a day or so.

**Comment by ppadovani** [comment]
Fixed and released

**Comment by huawangpp** [comment]
Thanks!
